#ref https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  language: en
  expandFocusedSidePanel: true
  border: hidden
  showPanelJumps: true
  showBottomLine: false
  nerdFontsVersion: "3"
  timeFormat: "06-01-02" #ref https://pkg.go.dev/time#Time.Format
  shortTimeFormat: "3:04PM"
  branchColors:
    "prod": "#A459D1"
    "hotfix": "#A94656"
    "release": "#FFB84C"
    "feature": "#555555"
    "deploy": "#B0B0B0"
    "master": "white"
    "main": "white"
  authorColors:
    "deptno": white
  #ref https://github.com/catppuccin/lazygit/blob/65c3b60aafc12b2c88494e012dbb1404086484dd/themes-mergable/frappe/frappe-rosewater.yml
  theme:
    activeBorderColor:
      - "#f2d5cf"
      - bold
    inactiveBorderColor:
      - "#a5adce"
    optionsTextColor:
      - "#8caaee"
    selectedLineBgColor:
      - "#414559"
    selectedRangeBgColor:
      - "#414559"
    cherryPickedCommitBgColor:
      - "#51576d"
    cherryPickedCommitFgColor:
      - "#f2d5cf"
    unstagedChangesColor:
      - "#e78284"
    defaultFgColor:
      - "#c6d0f5"
    searchingActiveBorderColor:
      - "#e5c890"
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never
  merging:
    args: "--no-ff"
  commitPrefixes:
    zigbang-client:
      - pattern: "^\\w+\\/(\\w+-\\w+).*"
        replace: "[$1] "
    s.zigbang.com:
      - pattern: "^\\w+\\/(\\w+-\\w+).*"
        replace: "[$1] "
    house-partners-client:
      - pattern: "^\\w+\\/(\\w+-\\w+).*"
        replace: "[$1] "
    single-page:
      - pattern: "^\\w+\\/(\\w+-\\w+).*"
        replace: "[$1] "
  mainBranches: [master, main]
  autoRefresh: true
  autoFetch: true
keybinding:
  universal:
    quit: "<c-c>"
    togglePanel: "<tab>"
    nextTab: "l"
    prevTab: "h"
    nextBlock-alt: ""
    prevBlock-alt: ""
    nextScreenMode: "="
    prevScreenMode: "-"
customCommands:
  - key: a
    command: "git pull --rebase --autostash"
    context: localBranches
  - key: a
    command: "git la --author={{.Form.author | quote}}"
    context: commits
    description: "logs by author"
    prompts:
      - type: "input"
        title: "author"
        key: "author"
        suggestions:
          preset: authors
    output: terminal
  - key: b
    command: "tig blame {{.SelectedFile.Name}}"
    context: files
    description: "blame"
    output: terminal
  - key: G
    command: "gh pr list -w --{{.Form.To}} {{.SelectedLocalBranch.Name}}"
    context: localBranches
    description: "open github pr"
    prompts:
      - type: "menu"
        title: "* {{.SelectedLocalBranch.Name}}?"
        key: "To"
        options:
          - name: "base"
            value: "base"
          - name: "head"
            value: "head"
    output: terminal
  - key: G
    command: "gh pr list -w --{{.Form.To}} {{.SelectedRemoteBranch.Name}}"
    context: remoteBranches
    description: "open github pr"
    prompts:
      - type: "menu"
        title: "* {{.SelectedLocalBranch.Name}}?"
        key: "To"
        options:
          - name: "base"
            value: "base"
          - name: "head"
            value: "head"
    output: terminal
  - key: G
    command: "gh pr list -w --{{.Form.To}} {{.SelectedLocalBranch.Name}}"
    context: commits
    description: "open github pr"
    prompts:
      - type: "menu"
        title: "* {{.SelectedLocalBranch.Name}}?"
        key: "To"
        options:
          - name: "base"
            value: "base"
          - name: "head"
            value: "head"
    output: terminal
